# Generated by Django 3.2.7 on 2021-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
